apiVersion : apps/v1
kind: Deployment
metadata:
  name: "coolapi-deployment"
  namespace: coolapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "coolapi"
  template:
    metadata:
      labels:
        app: "coolapi"
    spec:
      containers:
        - name: "coolapi"
          image: "acrdam25112022.azurecr.io/coolapi:1.0.0"
          resources:
            limits:
              cpu: "1"
              memory: "32Mi"
            requests:
              cpu: "0.5"
              memory: "4Mi"
          ports:
          - containerPort: 3000
